---
- name: Ensure the .ssh directory exists for the user
  ansible.builtin.file:
    path: "/home/{{ target_ansible_user }}/.ssh"
    state: directory
    owner: "{{ target_ansible_user }}"
    group: "{{ target_ansible_group }}"
    mode: '0700'

- name: Add {{ ssh_public_key_path }} authorized key for {{ target_ansible_user }}
  authorized_key:
    user: "{{ target_ansible_user }}"
    state: present
    manage_dir: yes
    key: "{{ lookup('file',  ssh_public_key_path) }}"

- name: Debug Variables
  debug:
    msg:
      - "ssh_public_key_path: {{ ssh_public_key_path }}"
      - "target_ansible_user: {{ target_ansible_user }}"
