---
- name: Ensure {{ target_ansible_group }} group exists
  ansible.builtin.group:
    name: "{{ target_ansible_group }}"
    state: present
  become: true


- name: Ensure {{ target_ansible_user }} user exists
  ansible.builtin.user:
    name: "{{ target_ansible_user }}"
    password: "{{ target_ansible_user_hashed_password }}"
    groups: "{{ target_ansible_group }}"
    shell: /bin/bash
    createhome: true
    state: present
  become: true

