---
# tasks file for basic_server_setup



#Packages setup
- ansible.builtin.import_tasks: ./update_upgrade.yml
- ansible.builtin.import_tasks: ./install_basic_packages.yml
- ansible.builtin.import_tasks: ./tasks/configure_unattended_upgrades.yml



#Mashine config
- ansible.builtin.import_tasks: ./tasks/ntp_time_sync.yml
- ansible.builtin.import_tasks: ./tasks/setup_ufw.yml
- ansible.builtin.import_tasks: ./set_hostname.yml



#User config
- ansible.builtin.import_tasks: ./create_user.yml
- ansible.builtin.import_tasks: ./setup_sudo.yml
- ansible.builtin.import_tasks: ./add_ssh_key.yml
- ansible.builtin.import_tasks: ./configure_ssh.yml

